name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [nightly]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Components
      run: rustup component add clippy
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      # TODO - add -D warnings back in after async-std publishes task::blocking
      run: cargo clippy # -- -D warnings
    - name: Run tests
      run: cargo test --verbose
